# Generated by Django 6.0.3 on 2026-03-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('rating', models.FloatField(default=4.0)),
                ('open_now', models.BooleanField(default=True)),
                ('types', models.CharField(help_text='Comma-separated types, e.g. Phones,Batteries', max_length=500)),
            ],
        ),
    ]
