# Generated by Django 6.0.3 on 2026-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_recyclingcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='tracking_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('collected', 'Collected'), ('in-transit', 'In Transit'), ('at-facility', 'At Facility'), ('processed', 'Processed')], default='scheduled', max_length=20),
        ),
    ]
